server:
  port: 8080
  servlet:
    context-path: /devweek

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ekmjptqsjzptpu:d1e311765e6acb194e48d49f977a76df7909a3911f2049910920ab5cdac07a59@ec2-34-193-112-164.compute-1.amazonaws.com:5432/d85vd0toe4q8av
    username: ekmjptqsjzptpu
    password: d1e311765e6acb194e48d49f977a76df7909a3911f2049910920ab5cdac07a59
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander